<?xml version="1.0" encoding="utf-8"?><Database Name="asp" Class="DataConnectDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=asp;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="aspConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.companyinfo" Member="companyinfo">
    <Type Name="companyinfo">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="companyname" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="shortname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="scale" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="describe" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="director" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="varifyfile" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tag1" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="tag2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="tag3" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="verifystate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.userinfo" Member="userinfo">
    <Type Name="userinfo">
      <Column Name="email" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userstate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="token" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userregdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.challenge" Member="challenge">
    <Type Name="challenge">
      <Column Name="challengeid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengename" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="filepath" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tag1" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tag2" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tag3" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.personinfo" Member="personinfo">
    <Type Name="personinfo">
      <Column Name="userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="value" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.publishchallenge" Member="publishchallenge">
    <Type Name="publishchallenge">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ispublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="startdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="challengestate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recievenumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="enddate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="finishnumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publishid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="degree" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.recievechallenge" Member="recievechallenge">
    <Type Name="recievechallenge">
      <Column Name="userid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publishid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recievetime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="recievestatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recieveid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.viewchallenge1" Member="viewchallenge1">
    <Type Name="viewchallenge1">
      <Column Name="publishid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ispublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengestate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="companyname" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewChallengeState" Member="ViewChallengeState">
    <Type Name="ViewChallengeState">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="challengeid1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ispublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengestate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recievenumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengename2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="challengename3" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="challengename1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="publishid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="startdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="finishnumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="degree" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.viewcompany" Member="viewcompany">
    <Type Name="viewcompany">
      <Column Name="companyname" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="applytime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="verifystate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.viewusers" Member="viewusers">
    <Type Name="viewusers">
      <Column Name="email" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="value" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userstate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.viewchallenge" Member="viewchallenge">
    <Type Name="viewchallenge">
      <Column Name="type" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ispublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengeid3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengestate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="recievenumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="challengename2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="challengename3" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="challengename1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="publishid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="startdate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="enddate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="finishnumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="degree" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="shortname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="tag1" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="tag2" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="tag3" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
</Database>