#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36213
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="asp")]
	public partial class DataConnectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertcompanyinfo(companyinfo instance);
    partial void Updatecompanyinfo(companyinfo instance);
    partial void Deletecompanyinfo(companyinfo instance);
    partial void Insertuserinfo(userinfo instance);
    partial void Updateuserinfo(userinfo instance);
    partial void Deleteuserinfo(userinfo instance);
    partial void Insertrecievechallenge(recievechallenge instance);
    partial void Updaterecievechallenge(recievechallenge instance);
    partial void Deleterecievechallenge(recievechallenge instance);
    #endregion
		
		public DataConnectDataContext() : 
				base(global::DAL.Properties.Settings.Default.aspConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<companyinfo> companyinfo
		{
			get
			{
				return this.GetTable<companyinfo>();
			}
		}
		
		public System.Data.Linq.Table<userinfo> userinfo
		{
			get
			{
				return this.GetTable<userinfo>();
			}
		}
		
		public System.Data.Linq.Table<challenge> challenge
		{
			get
			{
				return this.GetTable<challenge>();
			}
		}
		
		public System.Data.Linq.Table<publishchallenge> publishchallenge
		{
			get
			{
				return this.GetTable<publishchallenge>();
			}
		}
		
		public System.Data.Linq.Table<recievechallenge> recievechallenge
		{
			get
			{
				return this.GetTable<recievechallenge>();
			}
		}
		
		public System.Data.Linq.Table<viewchallenge> viewchallenge
		{
			get
			{
				return this.GetTable<viewchallenge>();
			}
		}
		
		public System.Data.Linq.Table<personinfo> personinfo
		{
			get
			{
				return this.GetTable<personinfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.companyinfo")]
	public partial class companyinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _companyname;
		
		private string _shortname;
		
		private string _logo;
		
		private string _website;
		
		private string _province;
		
		private string _city;
		
		private string _scale;
		
		private string _describe;
		
		private string _director;
		
		private string _varifyfile;
		
		private string _tag1;
		
		private string _tag2;
		
		private string _tag3;
		
		private System.Nullable<int> _verifystate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OncompanynameChanging(string value);
    partial void OncompanynameChanged();
    partial void OnshortnameChanging(string value);
    partial void OnshortnameChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnscaleChanging(string value);
    partial void OnscaleChanged();
    partial void OndescribeChanging(string value);
    partial void OndescribeChanged();
    partial void OndirectorChanging(string value);
    partial void OndirectorChanged();
    partial void OnvarifyfileChanging(string value);
    partial void OnvarifyfileChanged();
    partial void Ontag1Changing(string value);
    partial void Ontag1Changed();
    partial void Ontag2Changing(string value);
    partial void Ontag2Changed();
    partial void Ontag3Changing(string value);
    partial void Ontag3Changed();
    partial void OnverifystateChanging(System.Nullable<int> value);
    partial void OnverifystateChanged();
    #endregion
		
		public companyinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="VarChar(40)")]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this.OncompanynameChanging(value);
					this.SendPropertyChanging();
					this._companyname = value;
					this.SendPropertyChanged("companyname");
					this.OncompanynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortname", DbType="VarChar(20)")]
		public string shortname
		{
			get
			{
				return this._shortname;
			}
			set
			{
				if ((this._shortname != value))
				{
					this.OnshortnameChanging(value);
					this.SendPropertyChanging();
					this._shortname = value;
					this.SendPropertyChanged("shortname");
					this.OnshortnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(100)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="VarChar(100)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(20)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="VarChar(20)")]
		public string scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this.OnscaleChanging(value);
					this.SendPropertyChanging();
					this._scale = value;
					this.SendPropertyChanged("scale");
					this.OnscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_describe", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string describe
		{
			get
			{
				return this._describe;
			}
			set
			{
				if ((this._describe != value))
				{
					this.OndescribeChanging(value);
					this.SendPropertyChanging();
					this._describe = value;
					this.SendPropertyChanged("describe");
					this.OndescribeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_director", DbType="VarChar(20)")]
		public string director
		{
			get
			{
				return this._director;
			}
			set
			{
				if ((this._director != value))
				{
					this.OndirectorChanging(value);
					this.SendPropertyChanging();
					this._director = value;
					this.SendPropertyChanged("director");
					this.OndirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_varifyfile", DbType="VarChar(100)")]
		public string varifyfile
		{
			get
			{
				return this._varifyfile;
			}
			set
			{
				if ((this._varifyfile != value))
				{
					this.OnvarifyfileChanging(value);
					this.SendPropertyChanging();
					this._varifyfile = value;
					this.SendPropertyChanged("varifyfile");
					this.OnvarifyfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag1", DbType="VarChar(40)")]
		public string tag1
		{
			get
			{
				return this._tag1;
			}
			set
			{
				if ((this._tag1 != value))
				{
					this.Ontag1Changing(value);
					this.SendPropertyChanging();
					this._tag1 = value;
					this.SendPropertyChanged("tag1");
					this.Ontag1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag2", DbType="VarChar(40)")]
		public string tag2
		{
			get
			{
				return this._tag2;
			}
			set
			{
				if ((this._tag2 != value))
				{
					this.Ontag2Changing(value);
					this.SendPropertyChanging();
					this._tag2 = value;
					this.SendPropertyChanged("tag2");
					this.Ontag2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag3", DbType="VarChar(40)")]
		public string tag3
		{
			get
			{
				return this._tag3;
			}
			set
			{
				if ((this._tag3 != value))
				{
					this.Ontag3Changing(value);
					this.SendPropertyChanging();
					this._tag3 = value;
					this.SendPropertyChanged("tag3");
					this.Ontag3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifystate", DbType="Int")]
		public System.Nullable<int> verifystate
		{
			get
			{
				return this._verifystate;
			}
			set
			{
				if ((this._verifystate != value))
				{
					this.OnverifystateChanging(value);
					this.SendPropertyChanging();
					this._verifystate = value;
					this.SendPropertyChanged("verifystate");
					this.OnverifystateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userinfo")]
	public partial class userinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _role;
		
		private System.Nullable<int> _userstate;
		
		private string _token;
		
		private int _userid;
		
		private System.Nullable<System.DateTime> _userregdate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(System.Nullable<int> value);
    partial void OnroleChanged();
    partial void OnuserstateChanging(System.Nullable<int> value);
    partial void OnuserstateChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnuserregdateChanging(System.Nullable<System.DateTime> value);
    partial void OnuserregdateChanged();
    #endregion
		
		public userinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int")]
		public System.Nullable<int> role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userstate", DbType="Int")]
		public System.Nullable<int> userstate
		{
			get
			{
				return this._userstate;
			}
			set
			{
				if ((this._userstate != value))
				{
					this.OnuserstateChanging(value);
					this.SendPropertyChanging();
					this._userstate = value;
					this.SendPropertyChanged("userstate");
					this.OnuserstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(255)")]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userregdate", DbType="Date")]
		public System.Nullable<System.DateTime> userregdate
		{
			get
			{
				return this._userregdate;
			}
			set
			{
				if ((this._userregdate != value))
				{
					this.OnuserregdateChanging(value);
					this.SendPropertyChanging();
					this._userregdate = value;
					this.SendPropertyChanged("userregdate");
					this.OnuserregdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.challenge")]
	public partial class challenge
	{
		
		private System.Nullable<int> _challengeid;
		
		private string _challengename;
		
		private string _filepath;
		
		private string _type;
		
		private System.Nullable<int> _level;
		
		public challenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid", DbType="Int")]
		public System.Nullable<int> challengeid
		{
			get
			{
				return this._challengeid;
			}
			set
			{
				if ((this._challengeid != value))
				{
					this._challengeid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename", DbType="VarChar(20)")]
		public string challengename
		{
			get
			{
				return this._challengename;
			}
			set
			{
				if ((this._challengename != value))
				{
					this._challengename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filepath", DbType="VarChar(40)")]
		public string filepath
		{
			get
			{
				return this._filepath;
			}
			set
			{
				if ((this._filepath != value))
				{
					this._filepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.publishchallenge")]
	public partial class publishchallenge
	{
		
		private System.Nullable<int> _userid;
		
		private System.Nullable<int> _publishid;
		
		private string _type;
		
		private System.Nullable<int> _level;
		
		private System.Nullable<int> _ispublished;
		
		private System.Nullable<int> _challengeid1;
		
		private System.Nullable<int> _challengeid2;
		
		private System.Nullable<int> _challengeid3;
		
		private string _startdate;
		
		private System.Nullable<int> _challengestate;
		
		private System.Nullable<int> _recievenumber;
		
		private string _enddate;
		
		private string _salary;
		
		public publishchallenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int")]
		public System.Nullable<int> publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this._publishid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublished", DbType="Int")]
		public System.Nullable<int> ispublished
		{
			get
			{
				return this._ispublished;
			}
			set
			{
				if ((this._ispublished != value))
				{
					this._ispublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid1", DbType="Int")]
		public System.Nullable<int> challengeid1
		{
			get
			{
				return this._challengeid1;
			}
			set
			{
				if ((this._challengeid1 != value))
				{
					this._challengeid1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid2", DbType="Int")]
		public System.Nullable<int> challengeid2
		{
			get
			{
				return this._challengeid2;
			}
			set
			{
				if ((this._challengeid2 != value))
				{
					this._challengeid2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid3", DbType="Int")]
		public System.Nullable<int> challengeid3
		{
			get
			{
				return this._challengeid3;
			}
			set
			{
				if ((this._challengeid3 != value))
				{
					this._challengeid3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="VarChar(20)")]
		public string startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this._startdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengestate", DbType="Int")]
		public System.Nullable<int> challengestate
		{
			get
			{
				return this._challengestate;
			}
			set
			{
				if ((this._challengestate != value))
				{
					this._challengestate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievenumber", DbType="Int")]
		public System.Nullable<int> recievenumber
		{
			get
			{
				return this._recievenumber;
			}
			set
			{
				if ((this._recievenumber != value))
				{
					this._recievenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddate", DbType="VarChar(20)")]
		public string enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				if ((this._enddate != value))
				{
					this._enddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(20)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.recievechallenge")]
	public partial class recievechallenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _userid;
		
		private System.Nullable<int> _publishid;
		
		private System.Nullable<System.DateTime> _recievetime;
		
		private System.Nullable<int> _recievestatus;
		
		private System.Nullable<int> _grade;
		
		private int _recieveid;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OnpublishidChanging(System.Nullable<int> value);
    partial void OnpublishidChanged();
    partial void OnrecievetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnrecievetimeChanged();
    partial void OnrecievestatusChanging(System.Nullable<int> value);
    partial void OnrecievestatusChanged();
    partial void OngradeChanging(System.Nullable<int> value);
    partial void OngradeChanged();
    partial void OnrecieveidChanging(int value);
    partial void OnrecieveidChanged();
    #endregion
		
		public recievechallenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int")]
		public System.Nullable<int> publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this.OnpublishidChanging(value);
					this.SendPropertyChanging();
					this._publishid = value;
					this.SendPropertyChanged("publishid");
					this.OnpublishidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievetime", DbType="Date")]
		public System.Nullable<System.DateTime> recievetime
		{
			get
			{
				return this._recievetime;
			}
			set
			{
				if ((this._recievetime != value))
				{
					this.OnrecievetimeChanging(value);
					this.SendPropertyChanging();
					this._recievetime = value;
					this.SendPropertyChanged("recievetime");
					this.OnrecievetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievestatus", DbType="Int")]
		public System.Nullable<int> recievestatus
		{
			get
			{
				return this._recievestatus;
			}
			set
			{
				if ((this._recievestatus != value))
				{
					this.OnrecievestatusChanging(value);
					this.SendPropertyChanging();
					this._recievestatus = value;
					this.SendPropertyChanged("recievestatus");
					this.OnrecievestatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int recieveid
		{
			get
			{
				return this._recieveid;
			}
			set
			{
				if ((this._recieveid != value))
				{
					this.OnrecieveidChanging(value);
					this.SendPropertyChanging();
					this._recieveid = value;
					this.SendPropertyChanged("recieveid");
					this.OnrecieveidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewchallenge")]
	public partial class viewchallenge
	{
		
		private System.Nullable<int> _userid;
		
		private string _type;
		
		private System.Nullable<int> _level;
		
		private System.Nullable<int> _challengeid1;
		
		private System.Nullable<int> _challengeid2;
		
		private System.Nullable<int> _ispublished;
		
		private System.Nullable<int> _challengeid3;
		
		private System.Nullable<int> _challengestate;
		
		private System.Nullable<int> _recievenumber;
		
		private string _shortname;
		
		private string _logo;
		
		private string _tag1;
		
		private string _tag2;
		
		private string _tag3;
		
		private string _challengename2;
		
		private string _challengename3;
		
		private string _challengename1;
		
		private System.Nullable<int> _publishid;
		
		private string _startdate;
		
		private string _enddate;
		
		private string _salary;
		
		public viewchallenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid1", DbType="Int")]
		public System.Nullable<int> challengeid1
		{
			get
			{
				return this._challengeid1;
			}
			set
			{
				if ((this._challengeid1 != value))
				{
					this._challengeid1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid2", DbType="Int")]
		public System.Nullable<int> challengeid2
		{
			get
			{
				return this._challengeid2;
			}
			set
			{
				if ((this._challengeid2 != value))
				{
					this._challengeid2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublished", DbType="Int")]
		public System.Nullable<int> ispublished
		{
			get
			{
				return this._ispublished;
			}
			set
			{
				if ((this._ispublished != value))
				{
					this._ispublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid3", DbType="Int")]
		public System.Nullable<int> challengeid3
		{
			get
			{
				return this._challengeid3;
			}
			set
			{
				if ((this._challengeid3 != value))
				{
					this._challengeid3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengestate", DbType="Int")]
		public System.Nullable<int> challengestate
		{
			get
			{
				return this._challengestate;
			}
			set
			{
				if ((this._challengestate != value))
				{
					this._challengestate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievenumber", DbType="Int")]
		public System.Nullable<int> recievenumber
		{
			get
			{
				return this._recievenumber;
			}
			set
			{
				if ((this._recievenumber != value))
				{
					this._recievenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortname", DbType="VarChar(20)")]
		public string shortname
		{
			get
			{
				return this._shortname;
			}
			set
			{
				if ((this._shortname != value))
				{
					this._shortname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(100)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this._logo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag1", DbType="VarChar(40)")]
		public string tag1
		{
			get
			{
				return this._tag1;
			}
			set
			{
				if ((this._tag1 != value))
				{
					this._tag1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag2", DbType="VarChar(40)")]
		public string tag2
		{
			get
			{
				return this._tag2;
			}
			set
			{
				if ((this._tag2 != value))
				{
					this._tag2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag3", DbType="VarChar(40)")]
		public string tag3
		{
			get
			{
				return this._tag3;
			}
			set
			{
				if ((this._tag3 != value))
				{
					this._tag3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename2", DbType="VarChar(20)")]
		public string challengename2
		{
			get
			{
				return this._challengename2;
			}
			set
			{
				if ((this._challengename2 != value))
				{
					this._challengename2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename3", DbType="VarChar(20)")]
		public string challengename3
		{
			get
			{
				return this._challengename3;
			}
			set
			{
				if ((this._challengename3 != value))
				{
					this._challengename3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename1", DbType="VarChar(20)")]
		public string challengename1
		{
			get
			{
				return this._challengename1;
			}
			set
			{
				if ((this._challengename1 != value))
				{
					this._challengename1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int")]
		public System.Nullable<int> publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this._publishid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="VarChar(20)")]
		public string startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this._startdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddate", DbType="VarChar(20)")]
		public string enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				if ((this._enddate != value))
				{
					this._enddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(20)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personinfo")]
	public partial class personinfo
	{
		
		private System.Nullable<int> _userid;
		
		private string _username;
		
		private string _sex;
		
		private System.Nullable<int> _age;
		
		private string _phone;
		
		private System.Nullable<int> _value;
		
		private string _mail;
		
		public personinfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(1)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Int")]
		public System.Nullable<int> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(20)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this._mail = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
