#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36213
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="asp")]
	public partial class DataConnectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertuserinfo(userinfo instance);
    partial void Updateuserinfo(userinfo instance);
    partial void Deleteuserinfo(userinfo instance);
    partial void Insertpublishchallenge(publishchallenge instance);
    partial void Updatepublishchallenge(publishchallenge instance);
    partial void Deletepublishchallenge(publishchallenge instance);
    partial void Insertcompanyinfo(companyinfo instance);
    partial void Updatecompanyinfo(companyinfo instance);
    partial void Deletecompanyinfo(companyinfo instance);
    partial void Insertrecievechallenge(recievechallenge instance);
    partial void Updaterecievechallenge(recievechallenge instance);
    partial void Deleterecievechallenge(recievechallenge instance);
    #endregion
		
		public DataConnectDataContext() : 
				base(global::DAL.Properties.Settings.Default.aspConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataConnectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<userinfo> userinfo
		{
			get
			{
				return this.GetTable<userinfo>();
			}
		}
		
		public System.Data.Linq.Table<challenge> challenge
		{
			get
			{
				return this.GetTable<challenge>();
			}
		}
		
		public System.Data.Linq.Table<personinfo> personinfo
		{
			get
			{
				return this.GetTable<personinfo>();
			}
		}
		
		public System.Data.Linq.Table<publishchallenge> publishchallenge
		{
			get
			{
				return this.GetTable<publishchallenge>();
			}
		}
		
		public System.Data.Linq.Table<viewchallenge1> viewchallenge1
		{
			get
			{
				return this.GetTable<viewchallenge1>();
			}
		}
		
		public System.Data.Linq.Table<ViewChallengeState> ViewChallengeState
		{
			get
			{
				return this.GetTable<ViewChallengeState>();
			}
		}
		
		public System.Data.Linq.Table<viewcompany> viewcompany
		{
			get
			{
				return this.GetTable<viewcompany>();
			}
		}
		
		public System.Data.Linq.Table<viewusers> viewusers
		{
			get
			{
				return this.GetTable<viewusers>();
			}
		}
		
		public System.Data.Linq.Table<viewchallenge> viewchallenge
		{
			get
			{
				return this.GetTable<viewchallenge>();
			}
		}
		
		public System.Data.Linq.Table<companyinfo> companyinfo
		{
			get
			{
				return this.GetTable<companyinfo>();
			}
		}
		
		public System.Data.Linq.Table<recievechallenge> recievechallenge
		{
			get
			{
				return this.GetTable<recievechallenge>();
			}
		}
		
		public System.Data.Linq.Table<viewrecievechallenge> viewrecievechallenge
		{
			get
			{
				return this.GetTable<viewrecievechallenge>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userinfo")]
	public partial class userinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _role;
		
		private System.Nullable<int> _userstate;
		
		private string _token;
		
		private int _userid;
		
		private System.Nullable<System.DateTime> _userregdate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(System.Nullable<int> value);
    partial void OnroleChanged();
    partial void OnuserstateChanging(System.Nullable<int> value);
    partial void OnuserstateChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnuserregdateChanging(System.Nullable<System.DateTime> value);
    partial void OnuserregdateChanged();
    #endregion
		
		public userinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="Int")]
		public System.Nullable<int> role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userstate", DbType="Int")]
		public System.Nullable<int> userstate
		{
			get
			{
				return this._userstate;
			}
			set
			{
				if ((this._userstate != value))
				{
					this.OnuserstateChanging(value);
					this.SendPropertyChanging();
					this._userstate = value;
					this.SendPropertyChanged("userstate");
					this.OnuserstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(255)")]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userregdate", DbType="Date")]
		public System.Nullable<System.DateTime> userregdate
		{
			get
			{
				return this._userregdate;
			}
			set
			{
				if ((this._userregdate != value))
				{
					this.OnuserregdateChanging(value);
					this.SendPropertyChanging();
					this._userregdate = value;
					this.SendPropertyChanged("userregdate");
					this.OnuserregdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.challenge")]
	public partial class challenge
	{
		
		private System.Nullable<int> _challengeid;
		
		private string _challengename;
		
		private string _filepath;
		
		private string _type;
		
		private System.Nullable<int> _level;
		
		private string _tag1;
		
		private string _tag2;
		
		private string _tag3;
		
		public challenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid", DbType="Int")]
		public System.Nullable<int> challengeid
		{
			get
			{
				return this._challengeid;
			}
			set
			{
				if ((this._challengeid != value))
				{
					this._challengeid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename", DbType="VarChar(20)")]
		public string challengename
		{
			get
			{
				return this._challengename;
			}
			set
			{
				if ((this._challengename != value))
				{
					this._challengename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filepath", DbType="VarChar(40)")]
		public string filepath
		{
			get
			{
				return this._filepath;
			}
			set
			{
				if ((this._filepath != value))
				{
					this._filepath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(20)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag1", DbType="VarChar(10)")]
		public string tag1
		{
			get
			{
				return this._tag1;
			}
			set
			{
				if ((this._tag1 != value))
				{
					this._tag1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag2", DbType="VarChar(10)")]
		public string tag2
		{
			get
			{
				return this._tag2;
			}
			set
			{
				if ((this._tag2 != value))
				{
					this._tag2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag3", DbType="VarChar(10)")]
		public string tag3
		{
			get
			{
				return this._tag3;
			}
			set
			{
				if ((this._tag3 != value))
				{
					this._tag3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personinfo")]
	public partial class personinfo
	{
		
		private System.Nullable<int> _userid;
		
		private string _username;
		
		private string _sex;
		
		private System.Nullable<int> _age;
		
		private string _phone;
		
		private System.Nullable<int> _value;
		
		public personinfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(4)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Int")]
		public System.Nullable<int> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.publishchallenge")]
	public partial class publishchallenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _type;
		
		private System.Nullable<int> _level;
		
		private System.Nullable<int> _ispublished;
		
		private System.Nullable<int> _challengeid1;
		
		private System.Nullable<int> _challengeid2;
		
		private System.Nullable<int> _challengeid3;
		
		private string _startdate;
		
		private System.Nullable<int> _challengestate;
		
		private System.Nullable<int> _recievenumber;
		
		private string _enddate;
		
		private string _salary;
		
		private System.Nullable<int> _finishnumber;
		
		private int _publishid;
		
		private string _degree;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnlevelChanging(System.Nullable<int> value);
    partial void OnlevelChanged();
    partial void OnispublishedChanging(System.Nullable<int> value);
    partial void OnispublishedChanged();
    partial void Onchallengeid1Changing(System.Nullable<int> value);
    partial void Onchallengeid1Changed();
    partial void Onchallengeid2Changing(System.Nullable<int> value);
    partial void Onchallengeid2Changed();
    partial void Onchallengeid3Changing(System.Nullable<int> value);
    partial void Onchallengeid3Changed();
    partial void OnstartdateChanging(string value);
    partial void OnstartdateChanged();
    partial void OnchallengestateChanging(System.Nullable<int> value);
    partial void OnchallengestateChanged();
    partial void OnrecievenumberChanging(System.Nullable<int> value);
    partial void OnrecievenumberChanged();
    partial void OnenddateChanging(string value);
    partial void OnenddateChanged();
    partial void OnsalaryChanging(string value);
    partial void OnsalaryChanged();
    partial void OnfinishnumberChanging(System.Nullable<int> value);
    partial void OnfinishnumberChanged();
    partial void OnpublishidChanging(int value);
    partial void OnpublishidChanged();
    partial void OndegreeChanging(string value);
    partial void OndegreeChanged();
    #endregion
		
		public publishchallenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this.OnlevelChanging(value);
					this.SendPropertyChanging();
					this._level = value;
					this.SendPropertyChanged("level");
					this.OnlevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublished", DbType="Int")]
		public System.Nullable<int> ispublished
		{
			get
			{
				return this._ispublished;
			}
			set
			{
				if ((this._ispublished != value))
				{
					this.OnispublishedChanging(value);
					this.SendPropertyChanging();
					this._ispublished = value;
					this.SendPropertyChanged("ispublished");
					this.OnispublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid1", DbType="Int")]
		public System.Nullable<int> challengeid1
		{
			get
			{
				return this._challengeid1;
			}
			set
			{
				if ((this._challengeid1 != value))
				{
					this.Onchallengeid1Changing(value);
					this.SendPropertyChanging();
					this._challengeid1 = value;
					this.SendPropertyChanged("challengeid1");
					this.Onchallengeid1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid2", DbType="Int")]
		public System.Nullable<int> challengeid2
		{
			get
			{
				return this._challengeid2;
			}
			set
			{
				if ((this._challengeid2 != value))
				{
					this.Onchallengeid2Changing(value);
					this.SendPropertyChanging();
					this._challengeid2 = value;
					this.SendPropertyChanged("challengeid2");
					this.Onchallengeid2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid3", DbType="Int")]
		public System.Nullable<int> challengeid3
		{
			get
			{
				return this._challengeid3;
			}
			set
			{
				if ((this._challengeid3 != value))
				{
					this.Onchallengeid3Changing(value);
					this.SendPropertyChanging();
					this._challengeid3 = value;
					this.SendPropertyChanged("challengeid3");
					this.Onchallengeid3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="VarChar(20)")]
		public string startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this.OnstartdateChanging(value);
					this.SendPropertyChanging();
					this._startdate = value;
					this.SendPropertyChanged("startdate");
					this.OnstartdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengestate", DbType="Int")]
		public System.Nullable<int> challengestate
		{
			get
			{
				return this._challengestate;
			}
			set
			{
				if ((this._challengestate != value))
				{
					this.OnchallengestateChanging(value);
					this.SendPropertyChanging();
					this._challengestate = value;
					this.SendPropertyChanged("challengestate");
					this.OnchallengestateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievenumber", DbType="Int")]
		public System.Nullable<int> recievenumber
		{
			get
			{
				return this._recievenumber;
			}
			set
			{
				if ((this._recievenumber != value))
				{
					this.OnrecievenumberChanging(value);
					this.SendPropertyChanging();
					this._recievenumber = value;
					this.SendPropertyChanged("recievenumber");
					this.OnrecievenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddate", DbType="VarChar(20)")]
		public string enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				if ((this._enddate != value))
				{
					this.OnenddateChanging(value);
					this.SendPropertyChanging();
					this._enddate = value;
					this.SendPropertyChanged("enddate");
					this.OnenddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(20)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finishnumber", DbType="Int")]
		public System.Nullable<int> finishnumber
		{
			get
			{
				return this._finishnumber;
			}
			set
			{
				if ((this._finishnumber != value))
				{
					this.OnfinishnumberChanging(value);
					this.SendPropertyChanging();
					this._finishnumber = value;
					this.SendPropertyChanged("finishnumber");
					this.OnfinishnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this.OnpublishidChanging(value);
					this.SendPropertyChanging();
					this._publishid = value;
					this.SendPropertyChanged("publishid");
					this.OnpublishidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(10)")]
		public string degree
		{
			get
			{
				return this._degree;
			}
			set
			{
				if ((this._degree != value))
				{
					this.OndegreeChanging(value);
					this.SendPropertyChanging();
					this._degree = value;
					this.SendPropertyChanged("degree");
					this.OndegreeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewchallenge1")]
	public partial class viewchallenge1
	{
		
		private int _publishid;
		
		private string _type;
		
		private string _salary;
		
		private System.Nullable<int> _ispublished;
		
		private System.Nullable<int> _challengestate;
		
		private string _companyname;
		
		public viewchallenge1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int NOT NULL")]
		public int publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this._publishid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(20)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublished", DbType="Int")]
		public System.Nullable<int> ispublished
		{
			get
			{
				return this._ispublished;
			}
			set
			{
				if ((this._ispublished != value))
				{
					this._ispublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengestate", DbType="Int")]
		public System.Nullable<int> challengestate
		{
			get
			{
				return this._challengestate;
			}
			set
			{
				if ((this._challengestate != value))
				{
					this._challengestate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="VarChar(40)")]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this._companyname = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewChallengeState")]
	public partial class ViewChallengeState
	{
		
		private int _userid;
		
		private string _type;
		
		private System.Nullable<int> _challengeid1;
		
		private System.Nullable<int> _challengeid2;
		
		private System.Nullable<int> _ispublished;
		
		private System.Nullable<int> _challengeid3;
		
		private System.Nullable<int> _challengestate;
		
		private System.Nullable<int> _recievenumber;
		
		private string _challengename2;
		
		private string _challengename3;
		
		private string _challengename1;
		
		private int _publishid;
		
		private string _startdate;
		
		private System.Nullable<int> _finishnumber;
		
		private System.Nullable<int> _challengeid;
		
		private string _degree;
		
		public ViewChallengeState()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid1", DbType="Int")]
		public System.Nullable<int> challengeid1
		{
			get
			{
				return this._challengeid1;
			}
			set
			{
				if ((this._challengeid1 != value))
				{
					this._challengeid1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid2", DbType="Int")]
		public System.Nullable<int> challengeid2
		{
			get
			{
				return this._challengeid2;
			}
			set
			{
				if ((this._challengeid2 != value))
				{
					this._challengeid2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublished", DbType="Int")]
		public System.Nullable<int> ispublished
		{
			get
			{
				return this._ispublished;
			}
			set
			{
				if ((this._ispublished != value))
				{
					this._ispublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid3", DbType="Int")]
		public System.Nullable<int> challengeid3
		{
			get
			{
				return this._challengeid3;
			}
			set
			{
				if ((this._challengeid3 != value))
				{
					this._challengeid3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengestate", DbType="Int")]
		public System.Nullable<int> challengestate
		{
			get
			{
				return this._challengestate;
			}
			set
			{
				if ((this._challengestate != value))
				{
					this._challengestate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievenumber", DbType="Int")]
		public System.Nullable<int> recievenumber
		{
			get
			{
				return this._recievenumber;
			}
			set
			{
				if ((this._recievenumber != value))
				{
					this._recievenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename2", DbType="VarChar(20)")]
		public string challengename2
		{
			get
			{
				return this._challengename2;
			}
			set
			{
				if ((this._challengename2 != value))
				{
					this._challengename2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename3", DbType="VarChar(20)")]
		public string challengename3
		{
			get
			{
				return this._challengename3;
			}
			set
			{
				if ((this._challengename3 != value))
				{
					this._challengename3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename1", DbType="VarChar(20)")]
		public string challengename1
		{
			get
			{
				return this._challengename1;
			}
			set
			{
				if ((this._challengename1 != value))
				{
					this._challengename1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int NOT NULL")]
		public int publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this._publishid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="VarChar(20)")]
		public string startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this._startdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finishnumber", DbType="Int")]
		public System.Nullable<int> finishnumber
		{
			get
			{
				return this._finishnumber;
			}
			set
			{
				if ((this._finishnumber != value))
				{
					this._finishnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid", DbType="Int")]
		public System.Nullable<int> challengeid
		{
			get
			{
				return this._challengeid;
			}
			set
			{
				if ((this._challengeid != value))
				{
					this._challengeid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(10)")]
		public string degree
		{
			get
			{
				return this._degree;
			}
			set
			{
				if ((this._degree != value))
				{
					this._degree = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewcompany")]
	public partial class viewcompany
	{
		
		private string _companyname;
		
		private string _city;
		
		private System.Nullable<System.DateTime> _applytime;
		
		private int _userid;
		
		private string _email;
		
		private System.Nullable<int> _verifystate;
		
		public viewcompany()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="VarChar(40)")]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this._companyname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this._city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applytime", DbType="DateTime")]
		public System.Nullable<System.DateTime> applytime
		{
			get
			{
				return this._applytime;
			}
			set
			{
				if ((this._applytime != value))
				{
					this._applytime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifystate", DbType="Int")]
		public System.Nullable<int> verifystate
		{
			get
			{
				return this._verifystate;
			}
			set
			{
				if ((this._verifystate != value))
				{
					this._verifystate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewusers")]
	public partial class viewusers
	{
		
		private string _email;
		
		private int _userid;
		
		private string _username;
		
		private string _sex;
		
		private System.Nullable<int> _age;
		
		private string _phone;
		
		private System.Nullable<int> _value;
		
		private System.Nullable<int> _userstate;
		
		public viewusers()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(4)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this._age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Int")]
		public System.Nullable<int> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userstate", DbType="Int")]
		public System.Nullable<int> userstate
		{
			get
			{
				return this._userstate;
			}
			set
			{
				if ((this._userstate != value))
				{
					this._userstate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewchallenge")]
	public partial class viewchallenge
	{
		
		private string _type;
		
		private System.Nullable<int> _level;
		
		private System.Nullable<int> _challengeid1;
		
		private System.Nullable<int> _challengeid2;
		
		private System.Nullable<int> _ispublished;
		
		private System.Nullable<int> _challengeid3;
		
		private System.Nullable<int> _challengestate;
		
		private System.Nullable<int> _recievenumber;
		
		private string _challengename2;
		
		private string _challengename3;
		
		private string _challengename1;
		
		private int _publishid;
		
		private string _startdate;
		
		private string _enddate;
		
		private string _salary;
		
		private int _userid;
		
		private System.Nullable<int> _finishnumber;
		
		private string _degree;
		
		private string _shortname;
		
		private string _tag1;
		
		private string _tag2;
		
		private string _tag3;
		
		public viewchallenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(25)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[level]", Storage="_level", DbType="Int")]
		public System.Nullable<int> level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this._level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid1", DbType="Int")]
		public System.Nullable<int> challengeid1
		{
			get
			{
				return this._challengeid1;
			}
			set
			{
				if ((this._challengeid1 != value))
				{
					this._challengeid1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid2", DbType="Int")]
		public System.Nullable<int> challengeid2
		{
			get
			{
				return this._challengeid2;
			}
			set
			{
				if ((this._challengeid2 != value))
				{
					this._challengeid2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublished", DbType="Int")]
		public System.Nullable<int> ispublished
		{
			get
			{
				return this._ispublished;
			}
			set
			{
				if ((this._ispublished != value))
				{
					this._ispublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengeid3", DbType="Int")]
		public System.Nullable<int> challengeid3
		{
			get
			{
				return this._challengeid3;
			}
			set
			{
				if ((this._challengeid3 != value))
				{
					this._challengeid3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengestate", DbType="Int")]
		public System.Nullable<int> challengestate
		{
			get
			{
				return this._challengestate;
			}
			set
			{
				if ((this._challengestate != value))
				{
					this._challengestate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievenumber", DbType="Int")]
		public System.Nullable<int> recievenumber
		{
			get
			{
				return this._recievenumber;
			}
			set
			{
				if ((this._recievenumber != value))
				{
					this._recievenumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename2", DbType="VarChar(20)")]
		public string challengename2
		{
			get
			{
				return this._challengename2;
			}
			set
			{
				if ((this._challengename2 != value))
				{
					this._challengename2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename3", DbType="VarChar(20)")]
		public string challengename3
		{
			get
			{
				return this._challengename3;
			}
			set
			{
				if ((this._challengename3 != value))
				{
					this._challengename3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_challengename1", DbType="VarChar(20)")]
		public string challengename1
		{
			get
			{
				return this._challengename1;
			}
			set
			{
				if ((this._challengename1 != value))
				{
					this._challengename1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int NOT NULL")]
		public int publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this._publishid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startdate", DbType="VarChar(20)")]
		public string startdate
		{
			get
			{
				return this._startdate;
			}
			set
			{
				if ((this._startdate != value))
				{
					this._startdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enddate", DbType="VarChar(20)")]
		public string enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				if ((this._enddate != value))
				{
					this._enddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(20)")]
		public string salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finishnumber", DbType="Int")]
		public System.Nullable<int> finishnumber
		{
			get
			{
				return this._finishnumber;
			}
			set
			{
				if ((this._finishnumber != value))
				{
					this._finishnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(10)")]
		public string degree
		{
			get
			{
				return this._degree;
			}
			set
			{
				if ((this._degree != value))
				{
					this._degree = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortname", DbType="VarChar(20)")]
		public string shortname
		{
			get
			{
				return this._shortname;
			}
			set
			{
				if ((this._shortname != value))
				{
					this._shortname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag1", DbType="VarChar(40)")]
		public string tag1
		{
			get
			{
				return this._tag1;
			}
			set
			{
				if ((this._tag1 != value))
				{
					this._tag1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag2", DbType="VarChar(40)")]
		public string tag2
		{
			get
			{
				return this._tag2;
			}
			set
			{
				if ((this._tag2 != value))
				{
					this._tag2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag3", DbType="VarChar(40)")]
		public string tag3
		{
			get
			{
				return this._tag3;
			}
			set
			{
				if ((this._tag3 != value))
				{
					this._tag3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.companyinfo")]
	public partial class companyinfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private string _companyname;
		
		private string _shortname;
		
		private string _logo;
		
		private string _website;
		
		private string _province;
		
		private string _city;
		
		private string _scale;
		
		private string _describe;
		
		private string _director;
		
		private string _varifyfile;
		
		private string _tag1;
		
		private string _tag2;
		
		private string _tag3;
		
		private System.Nullable<int> _verifystate;
		
		private System.Nullable<System.DateTime> _applytime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OncompanynameChanging(string value);
    partial void OncompanynameChanged();
    partial void OnshortnameChanging(string value);
    partial void OnshortnameChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnscaleChanging(string value);
    partial void OnscaleChanged();
    partial void OndescribeChanging(string value);
    partial void OndescribeChanged();
    partial void OndirectorChanging(string value);
    partial void OndirectorChanged();
    partial void OnvarifyfileChanging(string value);
    partial void OnvarifyfileChanged();
    partial void Ontag1Changing(string value);
    partial void Ontag1Changed();
    partial void Ontag2Changing(string value);
    partial void Ontag2Changed();
    partial void Ontag3Changing(string value);
    partial void Ontag3Changed();
    partial void OnverifystateChanging(System.Nullable<int> value);
    partial void OnverifystateChanged();
    partial void OnapplytimeChanging(System.Nullable<System.DateTime> value);
    partial void OnapplytimeChanged();
    #endregion
		
		public companyinfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="VarChar(40)")]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this.OncompanynameChanging(value);
					this.SendPropertyChanging();
					this._companyname = value;
					this.SendPropertyChanged("companyname");
					this.OncompanynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortname", DbType="VarChar(20)")]
		public string shortname
		{
			get
			{
				return this._shortname;
			}
			set
			{
				if ((this._shortname != value))
				{
					this.OnshortnameChanging(value);
					this.SendPropertyChanging();
					this._shortname = value;
					this.SendPropertyChanged("shortname");
					this.OnshortnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(100)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="VarChar(100)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(20)")]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="VarChar(20)")]
		public string scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this.OnscaleChanging(value);
					this.SendPropertyChanging();
					this._scale = value;
					this.SendPropertyChanged("scale");
					this.OnscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_describe", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string describe
		{
			get
			{
				return this._describe;
			}
			set
			{
				if ((this._describe != value))
				{
					this.OndescribeChanging(value);
					this.SendPropertyChanging();
					this._describe = value;
					this.SendPropertyChanged("describe");
					this.OndescribeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_director", DbType="VarChar(20)")]
		public string director
		{
			get
			{
				return this._director;
			}
			set
			{
				if ((this._director != value))
				{
					this.OndirectorChanging(value);
					this.SendPropertyChanging();
					this._director = value;
					this.SendPropertyChanged("director");
					this.OndirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_varifyfile", DbType="VarChar(100)")]
		public string varifyfile
		{
			get
			{
				return this._varifyfile;
			}
			set
			{
				if ((this._varifyfile != value))
				{
					this.OnvarifyfileChanging(value);
					this.SendPropertyChanging();
					this._varifyfile = value;
					this.SendPropertyChanged("varifyfile");
					this.OnvarifyfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag1", DbType="VarChar(40)")]
		public string tag1
		{
			get
			{
				return this._tag1;
			}
			set
			{
				if ((this._tag1 != value))
				{
					this.Ontag1Changing(value);
					this.SendPropertyChanging();
					this._tag1 = value;
					this.SendPropertyChanged("tag1");
					this.Ontag1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag2", DbType="VarChar(40)")]
		public string tag2
		{
			get
			{
				return this._tag2;
			}
			set
			{
				if ((this._tag2 != value))
				{
					this.Ontag2Changing(value);
					this.SendPropertyChanging();
					this._tag2 = value;
					this.SendPropertyChanged("tag2");
					this.Ontag2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag3", DbType="VarChar(40)")]
		public string tag3
		{
			get
			{
				return this._tag3;
			}
			set
			{
				if ((this._tag3 != value))
				{
					this.Ontag3Changing(value);
					this.SendPropertyChanging();
					this._tag3 = value;
					this.SendPropertyChanged("tag3");
					this.Ontag3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verifystate", DbType="Int")]
		public System.Nullable<int> verifystate
		{
			get
			{
				return this._verifystate;
			}
			set
			{
				if ((this._verifystate != value))
				{
					this.OnverifystateChanging(value);
					this.SendPropertyChanging();
					this._verifystate = value;
					this.SendPropertyChanged("verifystate");
					this.OnverifystateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applytime", DbType="DateTime")]
		public System.Nullable<System.DateTime> applytime
		{
			get
			{
				return this._applytime;
			}
			set
			{
				if ((this._applytime != value))
				{
					this.OnapplytimeChanging(value);
					this.SendPropertyChanging();
					this._applytime = value;
					this.SendPropertyChanged("applytime");
					this.OnapplytimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.recievechallenge")]
	public partial class recievechallenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _userid;
		
		private int _publishid;
		
		private System.Nullable<System.DateTime> _recievetime;
		
		private System.Nullable<int> _recievestatus;
		
		private System.Nullable<int> _grade;
		
		private int _recieveid;
		
		private string _startetime;
		
		private System.Nullable<int> _spenttime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OnpublishidChanging(int value);
    partial void OnpublishidChanged();
    partial void OnrecievetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnrecievetimeChanged();
    partial void OnrecievestatusChanging(System.Nullable<int> value);
    partial void OnrecievestatusChanged();
    partial void OngradeChanging(System.Nullable<int> value);
    partial void OngradeChanged();
    partial void OnrecieveidChanging(int value);
    partial void OnrecieveidChanged();
    partial void OnstartetimeChanging(string value);
    partial void OnstartetimeChanged();
    partial void OnspenttimeChanging(System.Nullable<int> value);
    partial void OnspenttimeChanged();
    #endregion
		
		public recievechallenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int NOT NULL")]
		public int publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this.OnpublishidChanging(value);
					this.SendPropertyChanging();
					this._publishid = value;
					this.SendPropertyChanged("publishid");
					this.OnpublishidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievetime", DbType="Date")]
		public System.Nullable<System.DateTime> recievetime
		{
			get
			{
				return this._recievetime;
			}
			set
			{
				if ((this._recievetime != value))
				{
					this.OnrecievetimeChanging(value);
					this.SendPropertyChanging();
					this._recievetime = value;
					this.SendPropertyChanged("recievetime");
					this.OnrecievetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievestatus", DbType="Int")]
		public System.Nullable<int> recievestatus
		{
			get
			{
				return this._recievestatus;
			}
			set
			{
				if ((this._recievestatus != value))
				{
					this.OnrecievestatusChanging(value);
					this.SendPropertyChanging();
					this._recievestatus = value;
					this.SendPropertyChanged("recievestatus");
					this.OnrecievestatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int recieveid
		{
			get
			{
				return this._recieveid;
			}
			set
			{
				if ((this._recieveid != value))
				{
					this.OnrecieveidChanging(value);
					this.SendPropertyChanging();
					this._recieveid = value;
					this.SendPropertyChanged("recieveid");
					this.OnrecieveidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startetime", DbType="VarChar(20)")]
		public string startetime
		{
			get
			{
				return this._startetime;
			}
			set
			{
				if ((this._startetime != value))
				{
					this.OnstartetimeChanging(value);
					this.SendPropertyChanging();
					this._startetime = value;
					this.SendPropertyChanged("startetime");
					this.OnstartetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spenttime", DbType="Int")]
		public System.Nullable<int> spenttime
		{
			get
			{
				return this._spenttime;
			}
			set
			{
				if ((this._spenttime != value))
				{
					this.OnspenttimeChanging(value);
					this.SendPropertyChanging();
					this._spenttime = value;
					this.SendPropertyChanged("spenttime");
					this.OnspenttimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.viewrecievechallenge")]
	public partial class viewrecievechallenge
	{
		
		private int _userid;
		
		private int _publishid;
		
		private System.Nullable<System.DateTime> _recievetime;
		
		private System.Nullable<int> _recievestatus;
		
		private System.Nullable<int> _grade;
		
		private int _recieveid;
		
		private string _startetime;
		
		private System.Nullable<int> _spenttime;
		
		private string _username;
		
		private System.Nullable<int> _value;
		
		public viewrecievechallenge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int NOT NULL")]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this._userid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishid", DbType="Int NOT NULL")]
		public int publishid
		{
			get
			{
				return this._publishid;
			}
			set
			{
				if ((this._publishid != value))
				{
					this._publishid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievetime", DbType="Date")]
		public System.Nullable<System.DateTime> recievetime
		{
			get
			{
				return this._recievetime;
			}
			set
			{
				if ((this._recievetime != value))
				{
					this._recievetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recievestatus", DbType="Int")]
		public System.Nullable<int> recievestatus
		{
			get
			{
				return this._recievestatus;
			}
			set
			{
				if ((this._recievestatus != value))
				{
					this._recievestatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int")]
		public System.Nullable<int> grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this._grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieveid", DbType="Int NOT NULL")]
		public int recieveid
		{
			get
			{
				return this._recieveid;
			}
			set
			{
				if ((this._recieveid != value))
				{
					this._recieveid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startetime", DbType="VarChar(20)")]
		public string startetime
		{
			get
			{
				return this._startetime;
			}
			set
			{
				if ((this._startetime != value))
				{
					this._startetime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spenttime", DbType="Int")]
		public System.Nullable<int> spenttime
		{
			get
			{
				return this._spenttime;
			}
			set
			{
				if ((this._spenttime != value))
				{
					this._spenttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="Int")]
		public System.Nullable<int> value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
